// © 2025 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

// Schema extraction builds a resource's hint map from formae.fq.hints(clazz), which
// walks the resource class's own properties plus, recursively, the properties of any
// nested class that extends formae.SubResource. A nested class that does not extend
// formae.SubResource is skipped entirely, so its @gcp.FieldHint annotations never
// reach Schema.Hints and the conformance runner never learns which provider-populated
// nested fields are acceptable.
//
// These tests confirm nested hints reach Schema.Hints for classes that extend
// formae.SubResource, and that every class carrying a @gcp.FieldHint does.
//
// Run:
//
//	go test ./pkg/resources/registry/ -run TestNestedFieldHint -v
//
// No cloud credentials and no GCP resources are required.
package registry

import (
	"context"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"testing"

	"github.com/platform-engineering-labs/formae/pkg/plugin"
	"github.com/platform-engineering-labs/formae/pkg/plugin/descriptors"
)

// formaeSchemaPackage must match the dependency in schema/pkl/PklProject.
const formaeSchemaPackage = "package://hub.platform.engineering/plugins/pkl/schema/pkl/formae/formae@0.89.0"

func extractGCPDescriptors(t *testing.T) []plugin.ResourceTypeDescriptor {
	t.Helper()
	project, err := filepath.Abs(filepath.Join("..", "..", "..", "schema", "pkl", "PklProject"))
	if err != nil {
		t.Fatalf("resolve schema project path: %v", err)
	}
	// schema/pkl/VERSION is generated by `make build` (schema-version target) and gitignored.
	if _, err := os.Stat(filepath.Join(filepath.Dir(project), "VERSION")); err != nil {
		t.Skipf("schema/pkl/VERSION missing - run `make build` first (%v)", err)
	}
	ds, err := descriptors.ExtractSchema(context.Background(), []descriptors.Dependency{
		{Name: "formae", Value: formaeSchemaPackage},
		{Name: "gcp", Value: project},
	})
	if err != nil {
		t.Fatalf("ExtractSchema: %v", err)
	}
	return ds
}

func hintsFor(t *testing.T, ds []plugin.ResourceTypeDescriptor, resourceType string) map[string]any {
	t.Helper()
	for _, d := range ds {
		if d.Type == resourceType {
			out := make(map[string]any, len(d.Schema.Hints))
			for k, v := range d.Schema.Hints {
				out[k] = v
			}
			return out
		}
	}
	t.Fatalf("descriptor %q not found among %d extracted", resourceType, len(ds))
	return nil
}

// TestNestedFieldHintReachesSchema confirms that a @gcp.FieldHint on a field of a
// nested formae.SubResource class reaches Schema.Hints as the dotted path the
// conformance runner's isProviderDefault() looks up.
//
// schema/pkl/compute/instance.pkl carries @gcp.FieldHint { hasProviderDefault = true }
// (createOnly too, for the disk) on two paths nested inside GCP::Compute::Instance:
//
//	AttachedDisk.deviceName (via the disks property)
//	Metadata.fingerprint    (via the metadata property)
func TestNestedFieldHintReachesSchema(t *testing.T) {
	hints := hintsFor(t, extractGCPDescriptors(t), "GCP::Compute::Instance")

	wantNested := []string{
		"disks.deviceName",
		"metadata.fingerprint",
	}

	var missing []string
	for _, path := range wantNested {
		if _, ok := hints[path]; !ok {
			missing = append(missing, path)
		}
	}

	if len(missing) > 0 {
		var got []string
		for k := range hints {
			got = append(got, k)
		}
		sort.Strings(got)
		t.Errorf("%d of %d nested hint paths are missing from Schema.Hints.\n"+
			"  missing: %v\n"+
			"  Schema.Hints contains: %v",
			len(missing), len(wantNested), missing, got)
	}
}

// TestNoOrphanFieldHintClasses guards the invariant this package's schema now
// upholds: a class carrying a @gcp.FieldHint must extend, directly or
// transitively, formae.Resource or formae.SubResource. A class that does not is
// invisible to schema extraction, so any hint on it is silently inert. This is a
// local regression guard; formae core is expected to enforce the same invariant at
// schema-verification time.
func TestNoOrphanFieldHintClasses(t *testing.T) {
	root := filepath.Join("..", "..", "..", "schema", "pkl")
	orphans := findOrphanFieldHintClasses(t, root, "gcp")
	if len(orphans) > 0 {
		t.Errorf("%d class(es) carry @gcp.FieldHint but do not extend formae.Resource "+
			"or formae.SubResource, so their hints are silently dropped at extraction:\n%s",
			len(orphans), formatOrphans(orphans))
	}
}

type orphanClass struct {
	file  string
	class string
}

func formatOrphans(orphans []orphanClass) string {
	var out string
	for _, o := range orphans {
		out += "  " + o.file + ": " + o.class + "\n"
	}
	return out
}

// findOrphanFieldHintClasses parses the schema tree with a regex, not a real Pkl
// evaluator, mirroring the scope of a build-time regression guard rather than a
// full schema verifier. It resolves same-file "extends" chains and the formae SDK's
// own Secret (which extends Resource); a class extending something it cannot
// resolve is treated conservatively as reaching neither Resource nor SubResource,
// which would make it fail loudly here rather than pass silently.
func findOrphanFieldHintClasses(t *testing.T, root, pkg string) []orphanClass {
	t.Helper()

	classRe := regexp.MustCompile(`(?m)^\s*(?:open\s+)?class\s+(\w+)(?:\s*<[^>]*>)?\s*(?:extends\s+([\w.]+))?\s*\{`)
	hintRe := regexp.MustCompile(`@` + regexp.QuoteMeta(pkg) + `\.FieldHint\b`)

	type classInfo struct {
		extends string
		hasHint bool
	}
	files := map[string]map[string]classInfo{}

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Ext(path) != ".pkl" {
			return err
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, path)
		locs := classRe.FindAllStringSubmatchIndex(string(src), -1)
		classes := map[string]classInfo{}
		for i, loc := range locs {
			name := string(src[loc[2]:loc[3]])
			var extends string
			if loc[4] != -1 {
				extends = string(src[loc[4]:loc[5]])
			}
			end := len(src)
			if i+1 < len(locs) {
				end = locs[i+1][0]
			}
			body := string(src[loc[1]:end])
			classes[name] = classInfo{extends: extends, hasHint: hintRe.MatchString(body)}
		}
		files[rel] = classes
		return nil
	})
	if err != nil {
		t.Fatalf("walk schema: %v", err)
	}

	// formae SDK classes (referenced as "formae.X") known to reach Resource.
	sdkReachesResource := map[string]bool{
		"Secret": true,
	}

	var reaches func(rel, name string, seen map[string]bool) bool
	reaches = func(rel, name string, seen map[string]bool) bool {
		key := rel + "#" + name
		if seen[key] {
			return false
		}
		seen[key] = true
		if name == "Resource" || name == "SubResource" {
			return true
		}
		c, ok := files[rel][name]
		if !ok || c.extends == "" {
			return false
		}
		if dot := regexp.MustCompile(`^(\w+)\.(\w+)$`).FindStringSubmatch(c.extends); dot != nil {
			simple := dot[2]
			if simple == "Resource" || simple == "SubResource" {
				return true
			}
			if dot[1] == "formae" && sdkReachesResource[simple] {
				return true
			}
			return false
		}
		return reaches(rel, c.extends, seen)
	}

	var orphans []orphanClass
	for rel, classes := range files {
		for name, c := range classes {
			if c.hasHint && !reaches(rel, name, map[string]bool{}) {
				orphans = append(orphans, orphanClass{file: rel, class: name})
			}
		}
	}
	sort.Slice(orphans, func(i, j int) bool {
		if orphans[i].file != orphans[j].file {
			return orphans[i].file < orphans[j].file
		}
		return orphans[i].class < orphans[j].class
	})
	return orphans
}
